# TODO: run tests for plugins -- match property collision warnings, failing tests etc.
version: 2
jobs:
    build:
        steps:
            - checkout
            - yarn docs:build
            - run: cd docs/.vuepress/dist && echo 'docs.lipsurf.com' > CNAME && git init && git add -A && git commit -m 'deploy'
            - git push -f git@github.com:lipsurf/plugins.git master:gh-pages
